services:
  blogwiki:
    build:
      context: ..
      dockerfile: Dockerfile
    image: blogwiki:latest
    container_name: blogwiki
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.blogwiki.entrypoints=websecure"
      - "traefik.http.routers.blogwiki.rule=Host(`www.haisong.cc`) || Host(`haisong.cc`)"
      - "traefik.http.routers.blogwiki.tls=true"
      - "traefik.http.routers.blogwiki.tls.certresolver=dnsresolver"
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true
    name: traefik_net
